# Generated by Django 6.0.2 on 2026-02-25 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS_AG', "Soumis à l'AG"), ('VALIDE', 'Validé (AG)'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('budget_estime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget_vote', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('resolution_validation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_travaux', to='core.copropriete')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_locked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['copropriete', 'statut'], name='travaux_dos_copropr_5ef0ab_idx'), models.Index(fields=['copropriete', 'created_at'], name='travaux_dos_copropr_c74d4b_idx')],
                'unique_together': {('copropriete', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('adresse', models.TextField(blank=True, default='')),
                ('identifiant', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='core.copropriete')),
            ],
            options={
                'indexes': [models.Index(fields=['copropriete', 'nom'], name='travaux_fou_copropr_a6b0df_idx'), models.Index(fields=['copropriete', 'is_active'], name='travaux_fou_copropr_585dd5_idx')],
                'unique_together': {('copropriete', 'nom')},
            },
        ),
    ]
