# Generated by Django 6.0.2 on 2026-02-26 10:13

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('travaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dossiertravaux',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fournisseur',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dossiertravaux',
            name='budget_vote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget voté en AG (optionnel).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='dossiertravaux',
            name='resolution_validation_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID de la résolution AG qui valide ce dossier (placeholder).', null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='identifiant',
            field=models.CharField(blank=True, default='', help_text='RCCM / IFU / SIRET / etc.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='dossiertravaux',
            index=models.Index(fields=['copropriete', 'titre'], name='travaux_dos_copropr_b1a164_idx'),
        ),
        migrations.AddIndex(
            model_name='dossiertravaux',
            index=models.Index(fields=['copropriete', 'resolution_validation_id'], name='travaux_dos_copropr_28025b_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['copropriete', 'created_at'], name='travaux_fou_copropr_568561_idx'),
        ),
        migrations.AddConstraint(
            model_name='dossiertravaux',
            constraint=models.UniqueConstraint(fields=('copropriete', 'titre'), name='travaux_dossier_unique_titre_par_copro'),
        ),
        migrations.AddConstraint(
            model_name='dossiertravaux',
            constraint=models.CheckConstraint(condition=models.Q(('budget_estime__gte', Decimal('0.00'))), name='travaux_dossier_budget_estime_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dossiertravaux',
            constraint=models.CheckConstraint(condition=models.Q(('budget_vote__isnull', True), ('budget_vote__gte', Decimal('0.00')), _connector='OR'), name='travaux_dossier_budget_vote_null_or_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dossiertravaux',
            constraint=models.CheckConstraint(condition=models.Q(('budget_vote__isnull', True), ('budget_vote__lte', models.F('budget_estime')), _connector='OR'), name='travaux_dossier_budget_vote_lte_estime'),
        ),
        migrations.AddConstraint(
            model_name='fournisseur',
            constraint=models.UniqueConstraint(fields=('copropriete', 'nom'), name='travaux_fournisseur_unique_nom_par_copro'),
        ),
    ]
