# Generated by Django 6.0.2 on 2026-02-26 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0005_resolution_budget_vote_resolution_travaux_dossier_and_more'),
        ('core', '0001_initial'),
        ('travaux', '0002_alter_dossiertravaux_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1) On retire l'index historique (il portait sur l'ancien champ int)
        migrations.RemoveIndex(
            model_name='dossiertravaux',
            name='travaux_dos_copropr_28025b_idx',
        ),

        # 2) On RENOMME le champ Python, sans recréer de colonne
        #    La colonne DB reste "resolution_validation_id" (historique).
        migrations.RenameField(
            model_name='dossiertravaux',
            old_name='resolution_validation_id',
            new_name='resolution_validation',
        ),

        # 3) On transforme le type en OneToOneField en réutilisant la colonne existante
        migrations.AlterField(
            model_name='dossiertravaux',
            name='resolution_validation',
            field=models.OneToOneField(
                blank=True,
                null=True,
                help_text='Résolution AG qui valide ce dossier.',
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='dossier_travaux_validation',
                to='ag.resolution',
                db_column='resolution_validation_id',  # ✅ clé : réutilise la colonne existante
            ),
        ),

        # 4) On remet un index propre (même nom, maintenant sur le nouveau champ relation)
        migrations.AddIndex(
            model_name='dossiertravaux',
            index=models.Index(
                fields=['copropriete', 'resolution_validation'],
                name='travaux_dos_copropr_28025b_idx'
            ),
        ),

        # 5) Contraintes DB (comme tu avais)
        migrations.AddConstraint(
            model_name='dossiertravaux',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('statut', 'VALIDE'), _negated=True),
                    ('resolution_validation__isnull', False),
                    _connector='OR'
                ),
                name='travaux_dossier_valide_requires_resolution',
            ),
        ),
        migrations.AddConstraint(
            model_name='dossiertravaux',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('locked_at__isnull', True),
                    models.Q(('statut__in', ['BROUILLON', 'SOUMIS_AG']), _negated=True),
                    _connector='OR'
                ),
                name='travaux_dossier_locked_forbids_draft_or_submitted',
            ),
        ),
    ]