# Generated by Django 6.0.2 on 2026-02-26 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0005_resolution_budget_vote_resolution_travaux_dossier_and_more'),
        ('core', '0001_initial'),
        ('travaux', '0003_remove_dossiertravaux_travaux_dos_copropr_28025b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dossiertravaux',
            index=models.Index(fields=['copropriete', 'locked_at'], name='travaux_dos_copropr_0ab002_idx'),
        ),
    ]
