# Generated by Django 6.0.2 on 2026-02-27 12:30

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('travaux', '0004_dossiertravaux_travaux_dos_copropr_0ab002_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_paiement', models.DateField(default=datetime.date.today)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_travaux', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_travaux_created', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_travaux', to='travaux.dossiertravaux')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_travaux', to='travaux.fournisseur')),
            ],
            options={
                'ordering': ['-date_paiement', '-id'],
                'indexes': [models.Index(fields=['copropriete', 'date_paiement'], name='travaux_pai_copropr_a8b972_idx'), models.Index(fields=['copropriete', 'dossier'], name='travaux_pai_copropr_211b84_idx'), models.Index(fields=['copropriete', 'fournisseur'], name='travaux_pai_copropr_cb0bcc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', Decimal('0.00'))), name='travaux_paiement_montant_gt_0')],
            },
        ),
    ]
