# Generated by Django 6.0.2 on 2026-02-27 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travaux', '0005_paiementtravaux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravauxUnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField()),
                ('old_locked', models.BooleanField(default=True)),
                ('new_locked', models.BooleanField(default=False)),
                ('old_statut', models.CharField(blank=True, default='', max_length=30)),
                ('new_statut', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_logs', to='travaux.dossiertravaux')),
                ('unlocked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_unlock_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='travaux_tra_created_20719a_idx'), models.Index(fields=['dossier', 'created_at'], name='travaux_tra_dossier_486bc9_idx')],
            },
        ),
    ]
