# Generated by Django 6.0.2 on 2026-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_copromembre_options_alter_copropriete_options_and_more'),
        ('travaux', '0006_travauxunlocklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='specialite',
            field=models.CharField(blank=True, default='', help_text='Ex. plomberie, toiture, peinture, électricité...', max_length=255),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['copropriete', 'specialite'], name='travaux_fou_copropr_e4cd8f_idx'),
        ),
    ]
