# Generated by Django 6.0.2 on 2026-02-28 01:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_app', '0008_alter_ligneappeldefonds_montant_paye_and_more'),
        ('core', '0001_initial'),
        ('travaux', '0006_travauxunlocklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('banque', models.CharField(blank=True, max_length=120)),
                ('iban', models.CharField(blank=True, max_length=60)),
                ('rib', models.CharField(blank=True, max_length=60)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to='core.copropriete')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_operation', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('libelle', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='compta.comptebancaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_bancaires', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_bancaires_crees', to=settings.AUTH_USER_MODEL)),
                ('paiement_appel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_bancaires', to='billing_app.paiementappel')),
                ('paiement_travaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_bancaires', to='travaux.paiementtravaux')),
            ],
        ),
        migrations.AddIndex(
            model_name='comptebancaire',
            index=models.Index(fields=['copropriete', 'is_active'], name='compta_comp_copropr_d8f27e_idx'),
        ),
        migrations.AddIndex(
            model_name='comptebancaire',
            index=models.Index(fields=['copropriete', 'nom'], name='compta_comp_copropr_e9192a_idx'),
        ),
        migrations.AddConstraint(
            model_name='comptebancaire',
            constraint=models.UniqueConstraint(fields=('copropriete', 'nom'), name='uniq_compte_nom_par_copro'),
        ),
        migrations.AddIndex(
            model_name='mouvementbancaire',
            index=models.Index(fields=['copropriete', 'compte', 'date_operation'], name='compta_mouv_copropr_627dca_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementbancaire',
            index=models.Index(fields=['copropriete', 'sens', 'date_operation'], name='compta_mouv_copropr_0eee3f_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementbancaire',
            index=models.Index(fields=['copropriete', 'paiement_travaux'], name='compta_mouv_copropr_131ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementbancaire',
            index=models.Index(fields=['copropriete', 'paiement_appel'], name='compta_mouv_copropr_2c823d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementbancaire',
            constraint=models.CheckConstraint(condition=models.Q(('paiement_travaux__isnull', False), ('paiement_appel__isnull', False), _negated=True), name='chk_mvt_rapprochement_exclusif'),
        ),
    ]
