# Generated by Django 6.0.2 on 2026-02-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptebancaire',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='comptebancaire',
            index=models.Index(fields=['copropriete', 'is_default'], name='compta_comp_copropr_cb4351_idx'),
        ),
        migrations.AddConstraint(
            model_name='comptebancaire',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('copropriete',), name='uniq_compte_default_par_copro'),
        ),
    ]
