# Generated by Django 6.0.2 on 2026-02-28 11:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0002_comptebancaire_is_default_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='compta/releves/%Y/%m/')),
                ('fichier_nom', models.CharField(blank=True, max_length=255)),
                ('hash_unique', models.CharField(max_length=64)),
                ('encoding', models.CharField(blank=True, max_length=30)),
                ('delimiter', models.CharField(default=';', max_length=5)),
                ('nb_lignes', models.PositiveIntegerField(default=0)),
                ('nb_crees', models.PositiveIntegerField(default=0)),
                ('nb_ignores', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_imports', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_imports_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleveLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('date_valeur', models.DateField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('solde', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('hash_unique', models.CharField(max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('releve_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='compta.releveimport')),
            ],
            options={
                'ordering': ['-date_operation', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='releveimport',
            index=models.Index(fields=['copropriete', 'created_at'], name='compta_rele_copropr_d01d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='releveimport',
            index=models.Index(fields=['copropriete', 'hash_unique'], name='compta_rele_copropr_f55f9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='releveimport',
            constraint=models.UniqueConstraint(fields=('copropriete', 'hash_unique'), name='uniq_releveimport_hash_par_copro'),
        ),
        migrations.AddIndex(
            model_name='releveligne',
            index=models.Index(fields=['releve_import', 'date_operation'], name='compta_rele_releve__270a53_idx'),
        ),
        migrations.AddIndex(
            model_name='releveligne',
            index=models.Index(fields=['releve_import', 'sens'], name='compta_rele_releve__fc56c3_idx'),
        ),
        migrations.AddIndex(
            model_name='releveligne',
            index=models.Index(fields=['date_operation'], name='idx_releveligne_dateop'),
        ),
        migrations.AddConstraint(
            model_name='releveligne',
            constraint=models.UniqueConstraint(fields=('releve_import', 'hash_unique'), name='uniq_releveligne_hash_par_import'),
        ),
    ] 
