# Generated by Django 6.0.2 on 2026-02-28 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0003_releveimport_releveligne_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapprochementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cible', models.CharField(choices=[('PAIEMENT_APPEL', 'Paiement appel'), ('PAIEMENT_TRAVAUX', 'Paiement travaux'), ('MOUVEMENT', 'Mouvement bancaire')], max_length=30)),
                ('cible_id', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_operation', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('rapproche_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='releveligne',
            name='copropriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releves_lignes', to='core.copropriete'),
        ),
        migrations.AddField(
            model_name='releveligne',
            name='statut',
            field=models.CharField(choices=[('A_TRAITER', 'À traiter'), ('RAPPROCHE', 'Rapproché'), ('IGNORE', 'Ignoré')], default='A_TRAITER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='releveligne',
            index=models.Index(fields=['copropriete', 'statut'], name='compta_rele_copropr_0067f5_idx'),
        ),
        migrations.AddIndex(
            model_name='releveligne',
            index=models.Index(fields=['copropriete', 'date_operation'], name='compta_rele_copropr_a3dab0_idx'),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='copropriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements_bancaires', to='core.copropriete'),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='rapproche_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements_bancaires_faits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='releve_ligne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochement', to='compta.releveligne'),
        ),
        migrations.AddIndex(
            model_name='rapprochementbancaire',
            index=models.Index(fields=['copropriete', 'type_cible', 'cible_id'], name='compta_rapp_copropr_7a35cd_idx'),
        ),
        migrations.AddIndex(
            model_name='rapprochementbancaire',
            index=models.Index(fields=['copropriete', 'rapproche_at'], name='compta_rapp_copropr_8956c1_idx'),
        ),
    ]
