# Generated by Django 6.0.2 on 2026-02-28 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0004_rapprochementbancaire_releveligne_copropriete_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rapprochementbancaire',
            constraint=models.UniqueConstraint(fields=('releve_ligne',), name='uniq_rappro_par_releve_ligne'),
        ),
        migrations.AddConstraint(
            model_name='rapprochementbancaire',
            constraint=models.UniqueConstraint(fields=('copropriete', 'type_cible', 'cible_id'), name='uniq_rappro_cible_par_copro'),
        ),
    ]
