# Generated by Django 6.0.2 on 2026-02-28 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0005_rapprochementbancaire_uniq_rappro_par_releve_ligne_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements_bancaires_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='cancelled_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='rapprochementbancaire',
            index=models.Index(fields=['copropriete', 'is_cancelled'], name='compta_rapp_copropr_a0e20c_idx'),
        ),
    ]
