# Generated by Django 6.0.2 on 2026-02-28 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0006_rapprochementbancaire_cancelled_at_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rapprochementbancaire',
            name='uniq_rappro_cible_par_copro',
        ),
        migrations.AddConstraint(
            model_name='rapprochementbancaire',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('copropriete', 'type_cible', 'cible_id'), name='uniq_rappro_cible_active_par_copro'),
        ),
    ]
