# Generated by Django 6.0.2 on 2026-03-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0007_remove_rapprochementbancaire_uniq_rappro_cible_par_copro_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='previous_cible_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='previous_type_cible',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='retarget_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='retarget_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='retargeted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapprochementbancaire',
            name='retargeted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements_bancaires_retargetes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rapprochementbancaire',
            index=models.Index(fields=['copropriete', 'retargeted_at'], name='compta_rapp_copropr_7f4cf9_idx'),
        ),
    ]
