# Generated by Django 6.0.2 on 2026-03-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0008_rapprochementbancaire_previous_cible_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rapprochementbancaire',
            name='compta_rapp_copropr_7f4cf9_idx',
        ),
    ]
