# Generated by Django 6.0.2 on 2026-03-01 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0009_remove_rapprochementbancaire_compta_rapp_copropr_7f4cf9_idx'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rapprochementbancaire',
            index=models.Index(fields=['copropriete', 'retargeted_at'], name='compta_rapp_copropr_7f4cf9_idx'),
        ),
    ]
