# Generated by Django 6.0.2 on 2026-03-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0009_remove_paiementappel_uniq_paiement_reference_par_ligne_and_more'),
        ('compta', '0010_rapprochementbancaire_compta_rapp_copropr_7f4cf9_idx'),
        ('core', '0002_alter_copromembre_options_alter_copropriete_options_and_more'),
        ('travaux', '0006_travauxunlocklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementbancaire',
            name='cancel_kind',
            field=models.CharField(blank=True, choices=[('ERROR', "Annulation d'erreur"), ('BUSINESS', 'Annulation métier')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mouvementbancaire',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouvementbancaire',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_bancaires_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementbancaire',
            name='cancelled_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='mouvementbancaire',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='mouvementbancaire',
            index=models.Index(fields=['copropriete', 'is_cancelled'], name='compta_mouv_copropr_9ddda4_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementbancaire',
            index=models.Index(fields=['copropriete', 'cancel_kind'], name='compta_mouv_copropr_c44b20_idx'),
        ),
    ]
