# Generated by Django 6.0.2 on 2026-06-27 19:30

import apps.compta.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0011_mouvementbancaire_cancel_kind_and_more'),
        ('core', '0005_passwordresettoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DON', 'Don'), ('SUBVENTION', 'Subvention'), ('REMBOURSEMENT', 'Remboursement'), ('INTERET_BANCAIRE', 'Intérêt bancaire'), ('REGULARISATION_CREDIT', 'Régularisation crédit'), ('AUTRE_ENTREE', "Autre entrée d'argent")], db_index=True, default='AUTRE_ENTREE', max_length=30)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_operation', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('libelle', models.CharField(max_length=220)),
                ('source_nom', models.CharField(blank=True, default='', help_text='Nom du donateur, organisme, prestataire ou source du remboursement.', max_length=180)),
                ('mode_paiement', models.CharField(choices=[('VIREMENT', 'Virement'), ('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile money'), ('CARTE', 'Carte'), ('AUTRE', 'Autre')], db_index=True, default='VIREMENT', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to=apps.compta.models.entree_argent_upload_to)),
                ('justificatif_nom_original', models.CharField(blank=True, default='', max_length=255)),
                ('justificatif_mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('justificatif_taille_octets', models.PositiveBigIntegerField(default=0)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, default='', max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_argent_annulees', to=settings.AUTH_USER_MODEL)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrees_argent', to='compta.comptebancaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_argent', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_argent_creees', to=settings.AUTH_USER_MODEL)),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entree_argent', to='compta.mouvementbancaire')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_argent_modifiees', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_argent_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'argent",
                'verbose_name_plural': "Entrées d'argent",
                'ordering': ['-date_operation', '-id'],
                'indexes': [models.Index(fields=['copropriete', 'type'], name='compta_entr_copropr_fdf546_idx'), models.Index(fields=['copropriete', 'statut'], name='compta_entr_copropr_77a2f8_idx'), models.Index(fields=['copropriete', 'compte', 'date_operation'], name='compta_entr_copropr_113993_idx'), models.Index(fields=['copropriete', 'mode_paiement'], name='compta_entr_copropr_e123f0_idx'), models.Index(fields=['date_operation'], name='compta_entr_date_op_6c6719_idx'), models.Index(fields=['created_at'], name='compta_entr_created_f07ea9_idx')],
            },
        ),
    ]
