# Generated by Django 6.0.2 on 2026-02-22 13:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_charges', to='core.copropriete')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('copropriete', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='core.copropriete')),
            ],
            options={
                'ordering': ['-annee'],
                'unique_together': {('copropriete', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('date_charge', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing_app.categoriecharge')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing_app.exercice')),
            ],
            options={
                'ordering': ['-date_charge'],
            },
        ),
        migrations.CreateModel(
            name='AppelDeFonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120)),
                ('type_appel', models.CharField(choices=[('PERIODIQUE', 'Périodique'), ('EXCEPTIONNEL', 'Exceptionnel')], default='PERIODIQUE', max_length=20)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('genere', models.BooleanField(default=False)),
                ('tantieme_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appels_de_fonds', to='lots.tantiemecategorie')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='billing_app.exercice')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneAppelDeFonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantiemes', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('statut', models.CharField(choices=[('IMPAYE', 'Impayé'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé')], default='IMPAYE', max_length=10)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='billing_app.appeldefonds')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_appels', to='lots.lot')),
            ],
            options={
                'ordering': ['lot_id'],
                'unique_together': {('appel', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='PaiementAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte'), ('AUTRE', 'Autre')], default='VIREMENT', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='billing_app.ligneappeldefonds')),
            ],
            options={
                'ordering': ['-date_paiement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RelanceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('APPEL', 'Appel'), ('AUTRE', 'Autre')], default='WHATSAPP', max_length=20)),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec'), ('REPONSE', 'Réponse'), ('REGLE', 'Réglé')], default='ENVOYEE', max_length=20)),
                ('message', models.TextField()),
                ('reference_externe', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances', to='billing_app.appeldefonds')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances_charges', to='lots.lot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
