# Generated by Django 6.0.2 on 2026-02-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancelot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relancelot',
            name='appel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relances', to='billing_app.appeldefonds'),
        ),
        migrations.AddIndex(
            model_name='relancelot',
            index=models.Index(fields=['lot', 'appel', 'created_at'], name='billing_app_lot_id_89f1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='relancelot',
            index=models.Index(fields=['statut', 'created_at'], name='billing_app_statut_14978b_idx'),
        ),
    ]
