# Generated by Django 6.0.2 on 2026-02-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_relancelot_updated_at_alter_relancelot_appel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancelot',
            name='numero',
            field=models.CharField(
                 max_length=20,
                null=True,        # ✅ IMPORTANT (évite que toutes les anciennes lignes aient "")
                blank=True,
                db_index=True,
                unique=True,    # ✅ ok car NULLs multiples autorisés (PostgreSQL)
            ),
        ),
    ]