# Generated by Django 6.0.2 on 2026-02-23 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_relancelot_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementappel',
            name='date_paiement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
