# Generated by Django 6.0.2 on 2026-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_alter_paiementappel_date_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementappel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='paiementappel',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('ligne', 'reference'), name='uniq_paiement_reference_par_ligne'),
        ),
    ]
