# Generated by Django 6.0.2 on 2026-02-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_alter_paiementappel_reference_and_more'),
        ('core', '0001_initial'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appeldefonds',
            index=models.Index(fields=['exercice', 'date_echeance'], name='billing_app_exercic_e08080_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneappeldefonds',
            index=models.Index(fields=['appel', 'statut'], name='billing_app_appel_i_7200b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneappeldefonds',
            index=models.Index(fields=['lot', 'statut'], name='billing_app_lot_id_296aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementappel',
            index=models.Index(fields=['ligne', 'date_paiement'], name='billing_app_ligne_i_a99e7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercice',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('copropriete',), name='uniq_exercice_actif_par_copropriete'),
        ),
    ]
