# Generated by Django 6.0.2 on 2026-02-23 21:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0007_relancelot_qr_token_relancelot_qr_token_created_at_and_more'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneappeldefonds',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='relancelot',
            index=models.Index(fields=['qr_token'], name='billing_app_qr_toke_f0a550_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneappeldefonds',
            constraint=models.CheckConstraint(condition=models.Q(('montant_paye__gte', Decimal('0.00')), ('montant_paye__lte', models.F('montant_du'))), name='chk_ligne_montant_paye_lte_montant_du'),
        ),
        migrations.AddConstraint(
            model_name='relancelot',
            constraint=models.UniqueConstraint(fields=('lot', 'appel'), name='uniq_relance_lot_appel'),
        ),
    ]
