# Generated by Django 6.0.2 on 2026-03-01 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0008_alter_ligneappeldefonds_montant_paye_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paiementappel',
            name='uniq_paiement_reference_par_ligne',
        ),
        migrations.AddField(
            model_name='paiementappel',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementappel',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_appel_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiementappel',
            name='cancelled_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='paiementappel',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='paiementappel',
            index=models.Index(fields=['ligne', 'is_cancelled'], name='billing_app_ligne_i_937f12_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiementappel',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('reference', ''), _negated=True), ('is_cancelled', False)), fields=('ligne', 'reference'), name='uniq_paiement_reference_par_ligne_actif'),
        ),
    ]
