# Generated by Django 6.0.2 on 2026-02-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('type_lot', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('PARKING', 'Parking'), ('CAVE', 'Cave'), ('COMMERCE', 'Commerce'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etage', models.CharField(blank=True, max_length=20)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.copropriete')),
            ],
            options={
                'unique_together': {('copropriete', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='TantiemeCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tantieme_categories', to='core.copropriete')),
            ],
            options={
                'unique_together': {('copropriete', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LotTantieme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField()),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.copropriete')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tantiemes', to='lots.lot')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.tantiemecategorie')),
            ],
            options={
                'unique_together': {('lot', 'categorie')},
            },
        ),
    ]
