# Generated by Django 6.0.2 on 2026-02-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lottantieme',
            unique_together={('copropriete', 'lot', 'categorie')},
        ),
    ]
