# Generated by Django 6.0.2 on 2026-02-20 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('lots', '0002_alter_lottantieme_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lottantieme',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lottantieme',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_tantiemes', to='lots.tantiemecategorie'),
        ),
        migrations.AlterField(
            model_name='lottantieme',
            name='copropriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_tantiemes', to='core.copropriete'),
        ),
        migrations.AlterUniqueTogether(
            name='lottantieme',
            unique_together={('lot', 'categorie')},
        ),
    ]
