# Generated by Django 6.0.2 on 2026-02-22 13:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_alter_lottantieme_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['reference']},
        ),
        migrations.AlterModelOptions(
            name='lottantieme',
            options={'ordering': ['lot_id', 'categorie_id']},
        ),
        migrations.AlterModelOptions(
            name='tantiemecategorie',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='lottantieme',
            name='copropriete',
        ),
        migrations.AddField(
            model_name='lot',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lottantieme',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_tantiemes', to='lots.tantiemecategorie'),
        ),
        migrations.AlterField(
            model_name='lottantieme',
            name='valeur',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='tantiemecategorie',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
