# Generated by Django 6.0.2 on 2026-03-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['reference'], 'verbose_name': 'Lot', 'verbose_name_plural': 'Lots'},
        ),
        migrations.AlterModelOptions(
            name='lottantieme',
            options={'ordering': ['lot_id', 'categorie_id'], 'verbose_name': 'Tantième de lot', 'verbose_name_plural': 'Tantièmes des lots'},
        ),
        migrations.AlterModelOptions(
            name='tantiemecategorie',
            options={'ordering': ['code'], 'verbose_name': 'Catégorie de tantième', 'verbose_name_plural': 'Catégories de tantièmes'},
        ),
    ]
