# Generated by Django 6.0.2 on 2026-05-27 19:39

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_copropriete_description_copropriete_email_contact_and_more'),
        ('lots', '0005_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ('reference', 'id'), 'verbose_name': 'Lot', 'verbose_name_plural': 'Lots'},
        ),
        migrations.AlterModelOptions(
            name='lottantieme',
            options={'ordering': ('lot_id', 'categorie_id'), 'verbose_name': 'Tantième de lot', 'verbose_name_plural': 'Tantièmes des lots'},
        ),
        migrations.AlterModelOptions(
            name='tantiemecategorie',
            options={'ordering': ('code', 'id'), 'verbose_name': 'Catégorie de tantième', 'verbose_name_plural': 'Catégories de tantièmes'},
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lottantieme',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tantiemecategorie',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lot',
            name='batiment',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lot',
            name='escalier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lot',
            name='numero',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro interne ou cadastral du lot si différent de la référence.', max_length=50),
        ),
        migrations.AddField(
            model_name='lot',
            name='porte',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lot',
            name='statut',
            field=models.CharField(choices=[('OCCUPE', 'Occupé'), ('VACANT', 'Vacant'), ('EN_TRAVAUX', 'En travaux'), ('INACTIF', 'Inactif')], db_index=True, default='OCCUPE', max_length=30),
        ),
        migrations.AddField(
            model_name='lot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lottantieme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lottantieme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tantiemecategorie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tantiemecategorie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tantiemecategorie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='etage',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='reference',
            field=models.CharField(db_index=True, help_text='Référence officielle du lot. Exemple : A-101, LOT-001.', max_length=50),
        ),
        migrations.AlterField(
            model_name='lot',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface en m².', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='lot',
            name='type_lot',
            field=models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('PARKING', 'Parking'), ('CAVE', 'Cave'), ('COMMERCE', 'Commerce'), ('BUREAU', 'Bureau'), ('DEPOT', 'Dépôt'), ('AUTRE', 'Autre')], db_index=True, default='APPARTEMENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='tantiemecategorie',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tantiemecategorie',
            name='code',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['copropriete', 'actif'], name='lots_lot_copropr_b35a92_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['copropriete', 'reference'], name='lots_lot_copropr_cdda0f_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['copropriete', 'type_lot'], name='lots_lot_copropr_60e4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['copropriete', 'statut'], name='lots_lot_copropr_f77d71_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['batiment', 'etage'], name='lots_lot_batimen_cc6fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='lottantieme',
            index=models.Index(fields=['lot', 'categorie'], name='lots_lottan_lot_id_cd614b_idx'),
        ),
        migrations.AddIndex(
            model_name='lottantieme',
            index=models.Index(fields=['categorie', 'valeur'], name='lots_lottan_categor_c3ad8a_idx'),
        ),
        migrations.AddIndex(
            model_name='tantiemecategorie',
            index=models.Index(fields=['copropriete', 'actif'], name='lots_tantie_copropr_1fed9a_idx'),
        ),
        migrations.AddIndex(
            model_name='tantiemecategorie',
            index=models.Index(fields=['copropriete', 'code'], name='lots_tantie_copropr_b59d0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('copropriete', 'reference'), name='uniq_lot_reference_par_copropriete'),
        ),
        migrations.AddConstraint(
            model_name='lottantieme',
            constraint=models.UniqueConstraint(fields=('lot', 'categorie'), name='uniq_tantieme_par_lot_et_categorie'),
        ),
        migrations.AddConstraint(
            model_name='tantiemecategorie',
            constraint=models.UniqueConstraint(fields=('copropriete', 'code'), name='uniq_tantieme_categorie_code_par_copropriete'),
        ),
    ]
