# Generated by Django 6.0.2 on 2026-06-06 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersecurityprofile'),
        ('lots', '0006_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='nombre_pieces',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nombre de pièces du logement. Champ optionnel, surtout utile pour les appartements.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['nombre_pieces'], name='lots_lot_nombre__5ea305_idx'),
        ),
    ]
