# Generated by Django 6.0.2 on 2026-03-15 12:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_app', '0009_remove_paiementappel_uniq_paiement_reference_par_ligne_and_more'),
        ('core', '0002_alter_copromembre_options_alter_copropriete_options_and_more'),
        ('lots', '0005_alter_lot_options_alter_lottantieme_options_and_more'),
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierImpaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_appel', models.CharField(blank=True, max_length=120)),
                ('date_echeance', models.DateField()),
                ('montant_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('EN_RETARD', 'En retard'), ('PARTIELLEMENT_PAYE', 'Partiellement payé'), ('PAYE', 'Payé'), ('REGULARISE', 'Régularisé'), ('FERME', 'Fermé')], db_index=True, default='A_PAYER', max_length=30)),
                ('niveau_relance', models.PositiveSmallIntegerField(default=0)),
                ('relances_count', models.PositiveIntegerField(default=0)),
                ('derniere_relance_at', models.DateTimeField(blank=True, null=True)),
                ('date_dernier_paiement', models.DateField(blank=True, null=True)),
                ('est_regularise', models.BooleanField(db_index=True, default=False)),
                ('regularise_at', models.DateTimeField(blank=True, null=True)),
                ('auto_relance_active', models.BooleanField(default=True)),
                ('commentaire_interne', models.TextField(blank=True)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_impayes', to='billing_app.appeldefonds')),
                ('coproprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_impayes', to='owners.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_impayes', to='core.copropriete')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_impayes', to='lots.lot')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvisRegularisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant_total_regle', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_regularisation', models.DateTimeField()),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PDF', 'PDF'), ('INTERNE', 'Interne')], default='INTERNE', max_length=20)),
                ('statut', models.CharField(choices=[('GENERE', 'Généré'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec')], db_index=True, default='GENERE', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='relances/avis_regularisation/')),
                ('envoye_at', models.DateTimeField(blank=True, null=True)),
                ('motif_echec', models.TextField(blank=True)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avis_regularisations', to='billing_app.appeldefonds')),
                ('coproprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avis_regularisations', to='owners.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_regularisations', to='core.copropriete')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_regularisations_generes', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avis_regularisations', to='lots.lot')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis_regularisation', to='relances.dossierimpaye')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.PositiveSmallIntegerField(default=1)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PDF', 'PDF'), ('SMS', 'SMS')], db_index=True, max_length=20)),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec'), ('ANNULEE', 'Annulée')], db_index=True, default='ENVOYEE', max_length=20)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('montant_du_message', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reste_a_payer_au_moment_envoi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='relances/pdfs/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_echec', models.DateTimeField(blank=True, null=True)),
                ('motif_echec', models.TextField(blank=True)),
                ('annulee_at', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_annulees', to=settings.AUTH_USER_MODEL)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relances_recouvrement', to='billing_app.appeldefonds')),
                ('coproprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relances', to='owners.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='core.copropriete')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='relances.dossierimpaye')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_envoyees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relances', to='lots.lot')),
            ],
            options={
                'ordering': ['-date_envoi', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='dossierimpaye',
            index=models.Index(fields=['copropriete', 'statut'], name='relances_do_copropr_197a79_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierimpaye',
            index=models.Index(fields=['copropriete', 'est_regularise'], name='relances_do_copropr_ac56e0_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierimpaye',
            index=models.Index(fields=['copropriete', 'date_echeance'], name='relances_do_copropr_111a24_idx'),
        ),
        migrations.AddConstraint(
            model_name='dossierimpaye',
            constraint=models.UniqueConstraint(fields=('appel', 'lot'), name='uniq_dossier_impaye_par_appel_et_lot'),
        ),
        migrations.AddIndex(
            model_name='avisregularisation',
            index=models.Index(fields=['copropriete', 'statut'], name='relances_av_copropr_54d97d_idx'),
        ),
        migrations.AddIndex(
            model_name='avisregularisation',
            index=models.Index(fields=['copropriete', 'date_regularisation'], name='relances_av_copropr_41cd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='relance',
            index=models.Index(fields=['copropriete', 'statut'], name='relances_re_copropr_6c0b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='relance',
            index=models.Index(fields=['copropriete', 'canal'], name='relances_re_copropr_ea45a4_idx'),
        ),
        migrations.AddIndex(
            model_name='relance',
            index=models.Index(fields=['dossier', 'niveau'], name='relances_re_dossier_43e220_idx'),
        ),
    ]
