# Generated by Django 6.0.2 on 2026-03-03 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copromembre',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='copropriete',
            options={'ordering': ('nom', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='copromembre',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='copropriete',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='copromembre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='copromembre',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='copromembre',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SYNDIC', 'Syndic'), ('COMPTABLE', 'Comptable'), ('CONSEIL', 'Conseil syndical'), ('COPROPRIETAIRE', 'Copropriétaire')], db_index=True, default='COPROPRIETAIRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='copropriete',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='copropriete',
            name='nom',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='copropriete',
            name='pays',
            field=models.CharField(db_index=True, default="Côte d'Ivoire", max_length=80),
        ),
        migrations.AlterField(
            model_name='copropriete',
            name='ville',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='copromembre',
            index=models.Index(fields=['copropriete', 'is_active'], name='core_coprom_copropr_a93031_idx'),
        ),
        migrations.AddIndex(
            model_name='copromembre',
            index=models.Index(fields=['copropriete', 'role'], name='core_coprom_copropr_f219d3_idx'),
        ),
        migrations.AddIndex(
            model_name='copromembre',
            index=models.Index(fields=['user', 'is_active'], name='core_coprom_user_id_f2a6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='copropriete',
            index=models.Index(fields=['is_active', 'nom'], name='core_coprop_is_acti_0981dc_idx'),
        ),
        migrations.AddIndex(
            model_name='copropriete',
            index=models.Index(fields=['pays', 'ville'], name='core_coprop_pays_c8f0d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='copromembre',
            constraint=models.UniqueConstraint(fields=('copropriete', 'user'), name='uniq_copro_membre_par_user'),
        ),
    ]
