# Generated by Django 6.0.2 on 2026-05-27 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_copromembre_options_alter_copropriete_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='copropriete',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='copropriete',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='copropriete',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant lisible utilisé pour les URLs ou références externes.', max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='copropriete',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('ARCHIVEE', 'Archivée')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='copropriete',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='copromembre',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SYNDIC', 'Syndic'), ('GESTIONNAIRE', 'Gestionnaire'), ('COMPTABLE', 'Comptable'), ('CONSEIL', 'Conseil syndical'), ('COPROPRIETAIRE', 'Copropriétaire')], db_index=True, default='COPROPRIETAIRE', max_length=30),
        ),
        migrations.AlterField(
            model_name='copropriete',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Compatibilité historique. Préférer aussi le champ statut côté produit.'),
        ),
        migrations.AddIndex(
            model_name='copromembre',
            index=models.Index(fields=['role', 'is_active'], name='core_coprom_role_c58aed_idx'),
        ),
        migrations.AddIndex(
            model_name='copropriete',
            index=models.Index(fields=['statut', 'nom'], name='core_coprop_statut_eb1fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='copropriete',
            index=models.Index(fields=['slug'], name='core_coprop_slug_31b3b7_idx'),
        ),
    ]
