# Generated by Django 6.0.2 on 2026-05-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_copropriete_description_copropriete_email_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('must_change_password', models.BooleanField(db_index=True, default=False, help_text="Si True, l'utilisateur doit changer son mot de passe à la prochaine connexion.")),
                ('temporary_password_created_at', models.DateTimeField(blank=True, help_text='Date de génération du dernier mot de passe temporaire.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['must_change_password'], name='core_userse_must_ch_1498e2_idx')],
            },
        ),
    ]
