# Generated by Django 6.0.2 on 2026-06-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersecurityprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_user_agent', models.TextField(blank=True)),
                ('consumed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consumed_user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='usersecurityprofile',
            name='temporary_password_created_at',
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersecurityprofile',
            name='must_change_password',
            field=models.BooleanField(db_index=True, default=False, help_text="Force l'utilisateur à changer son mot de passe avant d'utiliser les API métier."),
        ),
        migrations.AddIndex(
            model_name='usersecurityprofile',
            index=models.Index(fields=['password_changed_at'], name='core_userse_passwor_04e631_idx'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'created_at'], name='core_passwo_user_id_e38a53_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'used_at'], name='core_passwo_user_id_4113b3_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at', 'used_at'], name='core_passwo_expires_d6b8ca_idx'),
        ),
    ]
