# Generated by Django 6.0.2 on 2026-07-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copropriete',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo officiel de la copropriété, utilisé dans l'interface et les documents.", null=True, upload_to='coproprietes/logos/'),
        ),
    ]
