# Generated by Django 6.0.2 on 2026-05-30 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMasqueCoproprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_masques_coproprietaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document masqué copropriétaire',
                'verbose_name_plural': 'Documents masqués copropriétaires',
                'indexes': [models.Index(fields=['user', 'document_id'], name='documents_d_user_id_d060b7_idx'), models.Index(fields=['user', 'categorie'], name='documents_d_user_id_43e266_idx'), models.Index(fields=['hidden_at'], name='documents_d_hidden__063fab_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document_id'), name='unique_document_masque_par_user')],
            },
        ),
    ]
