# Generated by Django 6.0.2 on 2026-06-04 21:34

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0008_alter_vote_unique_together_and_more'),
        ('core', '0004_usersecurityprofile'),
        ('documents', '0001_initial'),
        ('lots', '0006_alter_lot_options_alter_lottantieme_options_and_more'),
        ('owners', '0003_coproprietaire_user_account_and_more'),
        ('relances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RELANCE_IMPAYE', 'Relance impayé'), ('MISE_EN_DEMEURE', 'Mise en demeure'), ('MANDAT_AG', 'Mandat AG'), ('CONVOCATION_AG', 'Convocation AG'), ('PV_AG', 'Procès-verbal AG'), ('RECU_PAIEMENT', 'Reçu de paiement'), ('AUTRE', 'Autre document')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(db_index=True, max_length=80, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.generated_document_upload_to)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('is_visible_to_owner', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('GENERE', 'Généré'), ('ENVOYE', 'Envoyé'), ('CONSULTE', 'Consulté'), ('ANNULE', 'Annulé'), ('ARCHIVE', 'Archivé')], db_index=True, default='GENERE', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents_created', to=settings.AUTH_USER_MODEL)),
                ('related_ag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='ag.assembleegenerale')),
                ('related_dossier_impaye', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='relances.dossierimpaye')),
                ('related_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='lots.lot')),
                ('related_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='owners.coproprietaire')),
                ('related_relance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='relances.relance')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['copropriete', 'document_type'], name='documents_g_copropr_6192fc_idx'), models.Index(fields=['copropriete', 'status'], name='documents_g_copropr_b5b5b5_idx'), models.Index(fields=['related_owner', 'is_visible_to_owner'], name='documents_g_related_62d473_idx'), models.Index(fields=['related_lot', 'is_visible_to_owner'], name='documents_g_related_72e7c4_idx'), models.Index(fields=['related_ag'], name='documents_g_related_b3276d_idx'), models.Index(fields=['related_dossier_impaye'], name='documents_g_related_adad9e_idx'), models.Index(fields=['created_at'], name='documents_g_created_8bd370_idx')],
            },
        ),
    ]
