# Generated by Django 6.0.2 on 2026-06-08 20:40

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordresettoken_and_more'),
        ('documents', '0002_generateddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglementTexteApplicable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('REGLEMENT_COPROPRIETE', 'Règlement de copropriété'), ('REGLEMENT_INTERIEUR', 'Règlement intérieur'), ('TEXTE_LOI', 'Texte de loi'), ('NOTE_SYNDIC', 'Note du syndic'), ('VIE_COMMUNE', 'Vie commune'), ('CHARGES_COTISATIONS', 'Charges et cotisations'), ('ASSEMBLEES_GENERALES', 'Assemblées générales'), ('TRAVAUX_ENTRETIEN', 'Travaux et entretien'), ('DOCUMENT_ADMINISTRATIF', 'Document administratif'), ('AUTRE', 'Autre')], db_index=True, default='AUTRE', max_length=50)),
                ('resume', models.TextField(blank=True, default='', help_text='Résumé court affichable dans les listes.')),
                ('contenu', models.TextField(blank=True, default='', help_text='Contenu textuel du règlement, texte ou document.')),
                ('fichier', models.FileField(blank=True, help_text='PDF ou document attaché optionnel.', null=True, upload_to=apps.documents.models.reglement_texte_upload_to)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], db_index=True, default='BROUILLON', max_length=30)),
                ('visible_coproprietaire', models.BooleanField(db_index=True, default=False, help_text='Si coché, le texte publié est visible côté copropriétaire.')),
                ('ordre_affichage', models.PositiveIntegerField(default=100, help_text="Permet de prioriser l'ordre d'affichage.")),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglement_textes_applicables', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglement_textes_created', to=settings.AUTH_USER_MODEL)),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglement_textes_publies', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglement_textes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Règlement ou texte applicable',
                'verbose_name_plural': 'Règlements et textes applicables',
                'ordering': ['ordre_affichage', 'categorie', '-date_publication', '-created_at'],
                'indexes': [models.Index(fields=['copropriete', 'categorie'], name='documents_r_copropr_915b43_idx'), models.Index(fields=['copropriete', 'statut'], name='documents_r_copropr_48a333_idx'), models.Index(fields=['copropriete', 'visible_coproprietaire'], name='documents_r_copropr_877102_idx'), models.Index(fields=['statut', 'visible_coproprietaire'], name='documents_r_statut_8c1f63_idx'), models.Index(fields=['ordre_affichage'], name='documents_r_ordre_a_f4216c_idx'), models.Index(fields=['date_publication'], name='documents_r_date_pu_c0d041_idx'), models.Index(fields=['created_at'], name='documents_r_created_db8a7e_idx')],
            },
        ),
    ]
