# Generated by Django 6.0.2 on 2026-06-27 18:43

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordresettoken_and_more'),
        ('documents', '0003_reglementtexteapplicable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_document_categories', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_document_categories_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_document_categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie de document administratif',
                'verbose_name_plural': 'Catégories de documents administratifs',
                'ordering': ['order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=apps.documents.models.administrative_document_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('visible_to_coproprietaires', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_documents', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_documents_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_documents_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.administrativedocumentcategory')),
            ],
            options={
                'verbose_name': 'Document administratif',
                'verbose_name_plural': 'Documents administratifs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='administrativedocumentcategory',
            index=models.Index(fields=['copropriete', 'is_active'], name='documents_a_copropr_51f596_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedocumentcategory',
            index=models.Index(fields=['order'], name='documents_a_order_9b88b3_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedocumentcategory',
            index=models.Index(fields=['created_at'], name='documents_a_created_f11213_idx'),
        ),
        migrations.AddConstraint(
            model_name='administrativedocumentcategory',
            constraint=models.UniqueConstraint(fields=('copropriete', 'code'), name='uniq_admin_doc_category_code_per_copropriete'),
        ),
        migrations.AddIndex(
            model_name='administrativedocument',
            index=models.Index(fields=['copropriete', 'visible_to_coproprietaires'], name='documents_a_copropr_ee52d7_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedocument',
            index=models.Index(fields=['copropriete', 'category'], name='documents_a_copropr_1c47f2_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedocument',
            index=models.Index(fields=['published_at'], name='documents_a_publish_93b19f_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedocument',
            index=models.Index(fields=['created_at'], name='documents_a_created_d382a3_idx'),
        ),
    ]
