# Generated by Django 6.0.2 on 2026-02-24 12:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_app', '0008_alter_ligneappeldefonds_montant_paye_and_more'),
        ('core', '0001_initial'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssembleeGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Assemblée Générale', max_length=160)),
                ('date_ag', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONVOQUEE', 'Convoquée'), ('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblees_generales', to='core.copropriete')),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assemblees_generales', to='billing_app.exercice')),
            ],
            options={
                'ordering': ['-date_ag', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PresenceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantiemes', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12)),
                ('present_ou_represente', models.BooleanField(default=True)),
                ('representant_nom', models.CharField(blank=True, max_length=120)),
                ('commentaire', models.TextField(blank=True)),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='ag.assembleegenerale')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences_ag', to='lots.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('titre', models.CharField(max_length=200)),
                ('texte', models.TextField(blank=True)),
                ('type_majorite', models.CharField(choices=[('SIMPLE', 'Majorité simple (POUR > CONTRE)'), ('ABSOLUE', 'Majorité absolue (POUR > 50% des exprimés)'), ('QUALIFIEE_2_3', 'Majorité qualifiée 2/3 (POUR >= 66.67% des exprimés)'), ('UNANIMITE', 'Unanimité (100% POUR)')], default='SIMPLE', max_length=20)),
                ('cloturee', models.BooleanField(default=False)),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='ag.assembleegenerale')),
                ('tantieme_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='lots.tantiemecategorie')),
            ],
            options={
                'ordering': ['ag_id', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(choices=[('POUR', 'Pour'), ('CONTRE', 'Contre'), ('ABSTENTION', 'Abstention')], max_length=12)),
                ('tantiemes', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_ag', to='lots.lot')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ag.resolution')),
            ],
        ),
        migrations.AddIndex(
            model_name='assembleegenerale',
            index=models.Index(fields=['copropriete', 'date_ag'], name='ag_assemble_copropr_30406f_idx'),
        ),
        migrations.AddIndex(
            model_name='assembleegenerale',
            index=models.Index(fields=['statut', 'date_ag'], name='ag_assemble_statut_86c516_idx'),
        ),
        migrations.AddIndex(
            model_name='presencelot',
            index=models.Index(fields=['ag', 'present_ou_represente'], name='ag_presence_ag_id_efa717_idx'),
        ),
        migrations.AddIndex(
            model_name='presencelot',
            index=models.Index(fields=['lot'], name='ag_presence_lot_id_e74297_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presencelot',
            unique_together={('ag', 'lot')},
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['ag', 'ordre'], name='ag_resoluti_ag_id_80b9b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resolution',
            unique_together={('ag', 'ordre')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['resolution', 'choix'], name='ag_vote_resolut_697c40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('resolution', 'lot')},
        ),
    ]
