# Generated by Django 6.0.2 on 2026-02-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0001_initial'),
        ('billing_app', '0008_alter_ligneappeldefonds_montant_paye_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleegenerale',
            name='cachet_image',
            field=models.ImageField(blank=True, null=True, upload_to='ag/cachets/'),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='president_nom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ag/pv/'),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_pdf_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='secretaire_nom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='signature_president',
            field=models.ImageField(blank=True, null=True, upload_to='ag/signatures/'),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='signature_secretaire',
            field=models.ImageField(blank=True, null=True, upload_to='ag/signatures/'),
        ),
        migrations.AddIndex(
            model_name='assembleegenerale',
            index=models.Index(fields=['pv_locked'], name='ag_assemble_pv_lock_d67719_idx'),
        ),
    ]
