# Generated by Django 6.0.2 on 2026-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0002_assembleegenerale_cachet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_signed_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ag/pv_signed/'),
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='pv_signer_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
