# Generated by Django 6.0.2 on 2026-02-25 21:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0004_assembleegenerale_closed_at_and_more'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
        ('travaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='budget_vote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='resolution',
            name='travaux_dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions_ag', to='travaux.dossiertravaux'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['travaux_dossier'], name='ag_resoluti_travaux_1a7b71_idx'),
        ),
    ]
