# Generated by Django 6.0.2 on 2026-02-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0005_resolution_budget_vote_resolution_travaux_dossier_and_more'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('resolution', 'lot', 'choix')},
        ),
    ]
