# Generated by Django 6.0.2 on 2026-03-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0006_alter_vote_unique_together'),
        ('lots', '0004_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleegenerale',
            name='tantieme_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assemblees_generales', to='lots.tantiemecategorie'),
        ),
    ]
