# Generated by Django 6.0.2 on 2026-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0007_assembleegenerale_tantieme_categorie'),
        ('lots', '0005_alter_lot_options_alter_lottantieme_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('resolution', 'lot')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['lot'], name='ag_vote_lot_id_a3a61f_idx'),
        ),
    ]
