# Generated by Django 6.0.2 on 2026-06-05 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0008_alter_vote_unique_together_and_more'),
        ('lots', '0006_alter_lot_options_alter_lottantieme_options_and_more'),
        ('owners', '0003_coproprietaire_user_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='coproprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes_ag', to='owners.coproprietaire'),
        ),
        migrations.AddField(
            model_name='vote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes_ag_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes_ag_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='source',
            field=models.CharField(choices=[('BACKOFFICE', 'Back-office syndic'), ('ESPACE_COPROPRIETAIRE', 'Espace copropriétaire')], default='BACKOFFICE', max_length=32),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['source'], name='ag_vote_source_68da74_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['created_by'], name='ag_vote_created_3efb88_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['coproprietaire'], name='ag_vote_copropr_f9549c_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['locked'], name='ag_vote_locked_74615e_idx'),
        ),
    ]
