# Generated by Django 6.0.2 on 2026-06-05 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0009_vote_coproprietaire_vote_created_by_vote_ip_address_and_more'),
        ('documents', '0002_generateddocument'),
        ('lots', '0006_alter_lot_options_alter_lottantieme_options_and_more'),
        ('owners', '0003_coproprietaire_user_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AGProcuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandataire_nom', models.CharField(max_length=160)),
                ('mandataire_telephone', models.CharField(blank=True, max_length=40)),
                ('mandataire_email', models.EmailField(blank=True, max_length=254)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurations', to='ag.assembleegenerale')),
                ('coproprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurations_ag', to='owners.coproprietaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_procurations_creees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurations_ag', to='documents.generateddocument')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurations_ag', to='lots.lot')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_procurations_rejetees', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_procurations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['ag', 'statut'], name='ag_agprocur_ag_id_992be6_idx'), models.Index(fields=['coproprietaire', 'statut'], name='ag_agprocur_copropr_1e644d_idx'), models.Index(fields=['lot', 'statut'], name='ag_agprocur_lot_id_043aea_idx'), models.Index(fields=['created_at'], name='ag_agprocur_created_d3b820_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut__in', ['EN_ATTENTE', 'VALIDEE'])), fields=('ag', 'lot'), name='uniq_ag_procuration_active_par_lot')],
            },
        ),
    ]
