# Generated by Django 6.0.2 on 2026-06-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0010_agprocuration'),
        ('core', '0005_passwordresettoken_and_more'),
        ('documents', '0003_reglementtexteapplicable'),
        ('lots', '0007_lot_nombre_pieces_lot_lots_lot_nombre__5ea305_idx'),
        ('owners', '0004_lotoccupant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgConvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=80, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('GENEREE', 'Générée'), ('ENVOYEE', 'Envoyée'), ('CONSULTEE', 'Consultée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('canal', models.CharField(choices=[('PLATEFORME', 'Plateforme'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PAPIER', 'Papier'), ('AUTRE', 'Autre')], default='PLATEFORME', max_length=20)),
                ('objet', models.CharField(blank=True, default='', max_length=180)),
                ('message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('consulted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='ag.assembleegenerale')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ag_convocations_annulees', to=settings.AUTH_USER_MODEL)),
                ('coproprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ag_convocations', to='owners.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ag_convocations', to='core.copropriete')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_convocations', to='documents.generateddocument')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ag_convocations_generees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ag_convocations', to='lots.lot')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ag_convocations_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['copropriete', 'ag'], name='ag_agconvoc_copropr_d0dbf1_idx'), models.Index(fields=['copropriete', 'statut'], name='ag_agconvoc_copropr_0f4938_idx'), models.Index(fields=['ag', 'statut'], name='ag_agconvoc_ag_id_594bf7_idx'), models.Index(fields=['coproprietaire', 'statut'], name='ag_agconvoc_copropr_a1e4e6_idx'), models.Index(fields=['lot', 'statut'], name='ag_agconvoc_lot_id_fa5600_idx'), models.Index(fields=['reference'], name='ag_agconvoc_referen_bc5df9_idx')],
                'constraints': [models.UniqueConstraint(fields=('ag', 'lot'), name='unique_ag_convocation_by_lot')],
            },
        ),
    ]
