# Generated by Django 6.0.2 on 2026-06-10 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0011_agconvocation'),
        ('core', '0005_passwordresettoken_and_more'),
        ('documents', '0003_reglementtexteapplicable'),
        ('lots', '0007_lot_nombre_pieces_lot_lots_lot_nombre__5ea305_idx'),
        ('owners', '0004_lotoccupant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agconvocation',
            name='unique_ag_convocation_by_lot',
        ),
        migrations.AddField(
            model_name='agconvocation',
            name='is_rectificative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agconvocation',
            name='motif_rectification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agconvocation',
            name='parent_convocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectificatives', to='ag.agconvocation'),
        ),
        migrations.AddField(
            model_name='agconvocation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='agconvocation',
            index=models.Index(fields=['ag', 'lot', 'version'], name='ag_agconvoc_ag_id_2934f9_idx'),
        ),
        migrations.AddIndex(
            model_name='agconvocation',
            index=models.Index(fields=['parent_convocation'], name='ag_agconvoc_parent__6185d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='agconvocation',
            constraint=models.UniqueConstraint(fields=('ag', 'lot', 'version'), name='unique_ag_convocation_by_lot_version'),
        ),
    ]
