# Generated by Django 6.0.2 on 2026-06-12 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0012_remove_agconvocation_unique_ag_convocation_by_lot_and_more'),
        ('core', '0005_passwordresettoken_and_more'),
        ('lots', '0007_lot_nombre_pieces_lot_lots_lot_nombre__5ea305_idx'),
        ('owners', '0004_lotoccupant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgConvocationPreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80, unique=True)),
                ('type_evenement', models.CharField(choices=[('NOTIFICATION', 'Notification'), ('CONSULTATION', 'Consultation')], max_length=30)),
                ('canal', models.CharField(choices=[('PLATEFORME', 'Plateforme'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PAPIER', 'Papier'), ('MANUEL', 'Manuel'), ('AUTRE', 'Autre')], default='PLATEFORME', max_length=30)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], default='SUCCES', max_length=20)),
                ('destinataire_email', models.EmailField(blank=True, default='', max_length=254)),
                ('destinataire_telephone', models.CharField(blank=True, default='', max_length=50)),
                ('objet', models.CharField(blank=True, default='', max_length=255)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves_convocations', to='ag.assembleegenerale')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='ag.agconvocation')),
                ('coproprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_convocations_ag', to='owners.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves_convocations_ag', to='core.copropriete')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_convocations_ag', to='lots.lot')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_convocations_ag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['copropriete', 'type_evenement'], name='ag_agconvoc_copropr_4749b9_idx'), models.Index(fields=['ag', 'type_evenement'], name='ag_agconvoc_ag_id_b7b5c4_idx'), models.Index(fields=['convocation', 'type_evenement'], name='ag_agconvoc_convoca_8ab76f_idx'), models.Index(fields=['coproprietaire', 'type_evenement'], name='ag_agconvoc_copropr_174bd9_idx'), models.Index(fields=['lot', 'type_evenement'], name='ag_agconvoc_lot_id_255d84_idx'), models.Index(fields=['created_at'], name='ag_agconvoc_created_ad3555_idx'), models.Index(fields=['reference'], name='ag_agconvoc_referen_e10bf7_idx')],
            },
        ),
    ]
