# Generated by Django 6.0.2 on 2026-06-27 19:08

import apps.reunions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_passwordresettoken_and_more'),
        ('documents', '0004_administrativedocumentcategory_and_more'),
        ('owners', '0004_lotoccupant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionRencontre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REUNION_INTERNE', 'Réunion interne de pilotage'), ('INFORMATION_CONCERTATION', 'Réunion d’information et de concertation'), ('RENCONTRE_FOURNISSEUR', 'Rencontre fournisseur / intervenant'), ('RENCONTRE_AUTORITE', 'Rencontre autorité / administration'), ('AUTRE', 'Autre')], db_index=True, default='REUNION_INTERNE', max_length=40)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROGRAMMEE', 'Programmée'), ('TENUE', 'Tenue'), ('PUBLIEE', 'Publiée'), ('ARCHIVEE', 'Archivée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=30)),
                ('titre', models.CharField(max_length=220)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('objet', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, default='', max_length=220)),
                ('compte_rendu', models.TextField(blank=True, default='')),
                ('decisions', models.TextField(blank=True, default='')),
                ('visible_coproprietaire', models.BooleanField(db_index=True, default=False)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions_rencontres', to='core.copropriete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_rencontres_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_rencontres_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réunion ou rencontre',
                'verbose_name_plural': 'Réunions et rencontres',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReunionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTERNE', 'Interne'), ('COPROPRIETAIRE', 'Copropriétaire'), ('OCCUPANT', 'Occupant / résident'), ('PRESTATAIRE', 'Prestataire'), ('AUTORITE', 'Autorité / administration'), ('AUTRE', 'Autre')], db_index=True, default='AUTRE', max_length=30)),
                ('nom_complet', models.CharField(max_length=180)),
                ('organisation', models.CharField(blank=True, default='', max_length=180)),
                ('fonction', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=60)),
                ('present', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coproprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_participations', to='owners.coproprietaire')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_participations', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='reunions.reunionrencontre')),
            ],
            options={
                'verbose_name': 'Participant réunion / rencontre',
                'verbose_name_plural': 'Participants réunions / rencontres',
                'ordering': ['ordre', 'nom_complet', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReunionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ORDRE_DU_JOUR', 'Ordre du jour'), ('COMPTE_RENDU', 'Compte rendu'), ('PV_SIMPLE', 'PV simple'), ('COURRIER', 'Courrier'), ('NOTE', 'Note'), ('PIECE_JOINTE', 'Pièce jointe'), ('AUTRE', 'Autre')], db_index=True, default='PIECE_JOINTE', max_length=30)),
                ('titre', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('fichier', models.FileField(blank=True, null=True, upload_to=apps.reunions.models.reunion_document_upload_to)),
                ('nom_fichier_original', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('taille_octets', models.PositiveBigIntegerField(default=0)),
                ('visible_coproprietaire', models.BooleanField(db_index=True, default=False)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_documents_created', to=settings.AUTH_USER_MODEL)),
                ('document_administratif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_documents', to='documents.administrativedocument')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reunions.reunionrencontre')),
            ],
            options={
                'verbose_name': 'Document de réunion / rencontre',
                'verbose_name_plural': 'Documents de réunions / rencontres',
                'ordering': ['ordre', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReunionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], db_index=True, default='A_FAIRE', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute')], db_index=True, default='NORMALE', max_length=20)),
                ('responsable_nom', models.CharField(blank=True, default='', max_length=180)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_actions_created', to=settings.AUTH_USER_MODEL)),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_actions_assignees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_actions_updated', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reunions.reunionrencontre')),
            ],
            options={
                'verbose_name': 'Action de réunion / rencontre',
                'verbose_name_plural': 'Actions de réunions / rencontres',
                'ordering': ['ordre', 'echeance', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reunionrencontre',
            index=models.Index(fields=['copropriete', 'type'], name='reunions_re_copropr_b1ac5b_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionrencontre',
            index=models.Index(fields=['copropriete', 'statut'], name='reunions_re_copropr_cdbc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionrencontre',
            index=models.Index(fields=['copropriete', 'visible_coproprietaire'], name='reunions_re_copropr_9652d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionrencontre',
            index=models.Index(fields=['date_debut'], name='reunions_re_date_de_033dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionrencontre',
            index=models.Index(fields=['date_publication'], name='reunions_re_date_pu_9b4d18_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionrencontre',
            index=models.Index(fields=['created_at'], name='reunions_re_created_878be3_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionparticipant',
            index=models.Index(fields=['reunion', 'type'], name='reunions_re_reunion_83318e_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionparticipant',
            index=models.Index(fields=['reunion', 'present'], name='reunions_re_reunion_7b5f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionparticipant',
            index=models.Index(fields=['created_at'], name='reunions_re_created_961345_idx'),
        ),
        migrations.AddIndex(
            model_name='reuniondocument',
            index=models.Index(fields=['reunion', 'type'], name='reunions_re_reunion_0d4ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='reuniondocument',
            index=models.Index(fields=['reunion', 'visible_coproprietaire'], name='reunions_re_reunion_3bee28_idx'),
        ),
        migrations.AddIndex(
            model_name='reuniondocument',
            index=models.Index(fields=['created_at'], name='reunions_re_created_9cf806_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionaction',
            index=models.Index(fields=['reunion', 'statut'], name='reunions_re_reunion_1e3cea_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionaction',
            index=models.Index(fields=['reunion', 'priorite'], name='reunions_re_reunion_85f16d_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionaction',
            index=models.Index(fields=['echeance'], name='reunions_re_echeanc_d9ef55_idx'),
        ),
        migrations.AddIndex(
            model_name='reunionaction',
            index=models.Index(fields=['created_at'], name='reunions_re_created_a7401f_idx'),
        ),
    ]
