# Generated by Django 6.0.2 on 2026-03-07 10:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_copromembre_options_alter_copropriete_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenoms', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('GARDIEN', 'Gardien'), ('GARDIEN_NUIT', 'Gardien de nuit'), ('AGENT_ENTRETIEN', "Agent d'entretien"), ('SYNDIC_LOCAL', 'Syndic local'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('role_libre', models.CharField(blank=True, default='', max_length=120)),
                ('telephone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='core.copropriete')),
            ],
            options={
                'ordering': ['nom', 'prenoms', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContratEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('PRESTATION', 'Prestation'), ('INTERIM', 'Intérim'), ('AUTRE', 'Autre')], default='CDD', max_length=20)),
                ('type_contrat_libre', models.CharField(blank=True, default='', max_length=120)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('TERMINE', 'Terminé'), ('ROMPU', 'Rompu')], default='BROUILLON', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='rh/contrats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='rh.employe')),
            ],
            options={
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['copropriete', 'statut'], name='rh_employe_copropr_f91ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['copropriete', 'role'], name='rh_employe_copropr_0dcf04_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['nom', 'prenoms'], name='rh_employe_nom_0a1caa_idx'),
        ),
        migrations.AddIndex(
            model_name='contratemploye',
            index=models.Index(fields=['employe', 'statut'], name='rh_contrate_employe_820217_idx'),
        ),
        migrations.AddIndex(
            model_name='contratemploye',
            index=models.Index(fields=['date_debut', 'date_fin'], name='rh_contrate_date_de_e55114_idx'),
        ),
    ]
