# Generated by Django 6.0.2 on 2026-02-20 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lots', '0003_alter_lottantieme_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coproprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coproprietaires', to='core.copropriete')),
            ],
            options={
                'unique_together': {('copropriete', 'nom', 'prenom')},
            },
        ),
        migrations.CreateModel(
            name='ProprietaireLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('principal', models.BooleanField(default=True)),
                ('coproprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_possedes', to='owners.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes_lots', to='core.copropriete')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to='lots.lot')),
            ],
            options={
                'unique_together': {('lot', 'coproprietaire', 'date_debut')},
            },
        ),
    ]
