# Generated by Django 6.0.2 on 2026-05-27 19:39

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_copropriete_description_copropriete_email_contact_and_more'),
        ('lots', '0006_alter_lot_options_alter_lottantieme_options_and_more'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coproprietaire',
            options={'ordering': ('nom', 'prenom', 'id')},
        ),
        migrations.AlterModelOptions(
            name='proprietairelot',
            options={'ordering': ('-date_debut', '-id')},
        ),
        migrations.AlterUniqueTogether(
            name='coproprietaire',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proprietairelot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='civilite',
            field=models.CharField(blank=True, choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('MLLE', 'Mademoiselle'), ('SOCIETE', 'Société'), ('AUTRE', 'Autre')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='pays',
            field=models.CharField(db_index=True, default="Côte d'Ivoire", max_length=80),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='raison_sociale',
            field=models.CharField(blank=True, db_index=True, help_text='Utilisé lorsque le copropriétaire est une personne morale.', max_length=180),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='type_personne',
            field=models.CharField(choices=[('PHYSIQUE', 'Personne physique'), ('MORALE', 'Personne morale')], db_index=True, default='PHYSIQUE', max_length=20),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='ville',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proprietairelot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietairelot',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proprietairelot',
            name='quote_part',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Quote-part de propriété sur le lot. Exemple : 100.00 ou 50.00.', max_digits=6),
        ),
        migrations.AddField(
            model_name='proprietairelot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='nom',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='prenom',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proprietairelot',
            name='date_debut',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='proprietairelot',
            name='date_fin',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='proprietairelot',
            name='principal',
            field=models.BooleanField(db_index=True, default=True, help_text='Contact principal du lot pour la période active.'),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['copropriete', 'actif'], name='owners_copr_copropr_baed4b_idx'),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['copropriete', 'nom', 'prenom'], name='owners_copr_copropr_99bbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['copropriete', 'type_personne'], name='owners_copr_copropr_697f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['email'], name='owners_copr_email_9b0142_idx'),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['telephone'], name='owners_copr_telepho_17dd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='proprietairelot',
            index=models.Index(fields=['copropriete', 'lot'], name='owners_prop_copropr_4cb20f_idx'),
        ),
        migrations.AddIndex(
            model_name='proprietairelot',
            index=models.Index(fields=['copropriete', 'coproprietaire'], name='owners_prop_copropr_8b6b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='proprietairelot',
            index=models.Index(fields=['lot', 'date_fin'], name='owners_prop_lot_id_0b703a_idx'),
        ),
        migrations.AddIndex(
            model_name='proprietairelot',
            index=models.Index(fields=['lot', 'principal', 'date_fin'], name='owners_prop_lot_id_86c5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='proprietairelot',
            index=models.Index(fields=['coproprietaire', 'date_fin'], name='owners_prop_copropr_7dde10_idx'),
        ),
        migrations.AddConstraint(
            model_name='coproprietaire',
            constraint=models.UniqueConstraint(fields=('copropriete', 'nom', 'prenom'), name='uniq_coproprietaire_nom_prenom_par_copro'),
        ),
        migrations.AddConstraint(
            model_name='proprietairelot',
            constraint=models.UniqueConstraint(fields=('lot', 'coproprietaire', 'date_debut'), name='uniq_proprietaire_lot_date_debut'),
        ),
    ]
