# Generated by Django 6.0.2 on 2026-05-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersecurityprofile'),
        ('owners', '0002_alter_coproprietaire_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coproprietaire',
            name='user_account',
            field=models.ForeignKey(blank=True, help_text='Compte utilisateur lié à cette fiche copropriétaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coproprietaire_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['user_account'], name='owners_copr_user_ac_78d7b6_idx'),
        ),
    ]
