# Generated by Django 6.0.2 on 2026-06-06 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersecurityprofile'),
        ('lots', '0007_lot_nombre_pieces_lot_lots_lot_nombre__5ea305_idx'),
        ('owners', '0003_coproprietaire_user_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotOccupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(db_index=True, max_length=120)),
                ('prenom', models.CharField(blank=True, db_index=True, max_length=120)),
                ('telephone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('statut_occupation', models.CharField(choices=[('PROPRIETAIRE_OCCUPANT', 'Propriétaire occupant'), ('LOCATAIRE', 'Locataire'), ('AYANT_DROIT', 'Ayant droit'), ('AUTRE', 'Autre')], db_index=True, default='PROPRIETAIRE_OCCUPANT', max_length=40)),
                ('occupant_principal', models.BooleanField(db_index=True, default=True, help_text='Occupant principal actif du lot.')),
                ('nombre_occupants', models.PositiveSmallIntegerField(blank=True, help_text="Nombre total d'occupants déclarés pour le logement.", null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_entree', models.DateField(blank=True, db_index=True, null=True)),
                ('date_sortie', models.DateField(blank=True, db_index=True, null=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=160)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('coproprietaire', models.ForeignKey(blank=True, help_text="Copropriétaire de référence si l'occupant est propriétaire occupant ou ayant droit lié à un copropriétaire.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants_declares', to='owners.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants_lots', to='core.copropriete')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='lots.lot')),
            ],
            options={
                'ordering': ('lot__reference', '-occupant_principal', '-date_entree', '-id'),
                'indexes': [models.Index(fields=['copropriete', 'actif'], name='owners_loto_copropr_a9bd07_idx'), models.Index(fields=['copropriete', 'statut_occupation'], name='owners_loto_copropr_0dc784_idx'), models.Index(fields=['lot', 'actif'], name='owners_loto_lot_id_3cc342_idx'), models.Index(fields=['lot', 'occupant_principal', 'actif'], name='owners_loto_lot_id_ff04e9_idx'), models.Index(fields=['nom', 'prenom'], name='owners_loto_nom_d2e8ee_idx'), models.Index(fields=['telephone'], name='owners_loto_telepho_bde956_idx'), models.Index(fields=['email'], name='owners_loto_email_bf0968_idx'), models.Index(fields=['date_entree', 'date_sortie'], name='owners_loto_date_en_9d9bac_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('actif', True), ('date_sortie__isnull', True), ('occupant_principal', True)), fields=('lot',), name='uniq_occupant_principal_actif_par_lot')],
            },
        ),
    ]
